### ISSUE TITLE
볼륨 설정한 경로 다운받은 mp4 파일 소유권이 root 인 현상

### ISSUE THREAD

**Issue by bbyongi** [yellowgg2/youngs-ytdl#1]
볼륨 설정한 경로 다운받은 mp4 파일 소유권이 root:root 입니다. 

> -rw-r--r-- 1 root root 168815110  4월  5 17:51 '2022년 출시된 신작 에뮬게임기! ... RGB10S.mp4'
> -rw-r--r-- 1 root root  38555078  4월  5 17:51 '애플 폴더블 - 함께해요 코리아.mp4'

environment: 의 PUID 와 PGID 를 정확하게 입력했는데도 root 저장되고 있어서
매번 sudo chown test:test * 입력해서 소유권 바꿔서 접근해야하는 상황입니다.

혹시, ytdl_bot 에서 저장한 mp4 파일 소유권이 PUID:GUID 로 지정 될 수 없는지 문의 드립니다.

> -rw-r--r-- 1 test test 168815110  4월  5 17:51 '2022년 출시된 신작 에뮬게임기! ... RGB10S.mp4'
> -rw-r--r-- 1 test test 38555078  4월  5 17:51 '애플 폴더블 - 함께해요 코리아.mp4'

감사합니다.

**Comment by yellowgg2** [comment]
@bbyongi 안녕하세요.

해당 문제 수정해서 올렸습니다.

기존 docker-compose.yml에 args 부분이 추가되었고 Dockerfile이 변경되었습니다.

기존에 쓰고 계시고 `docker-compose.yml`파일을 수정하셨다면 pull하셔도 파일 변경이 되지 않기 때문에, docker-compose.yml파일에 `args` 부분을 repo를 보시고 추가하시고 변경하세요.

그리고 아래 순서대로 진행하시면 됩니다.

1. `docker-compose down` 으로 컨테이너 삭제
2. `db/ytdl-bot.db` 파일의 권한이 `root` 라면 `chown`으로 소유권 변경
3. `download/` 폴더의 권한이 `root`라면 `chown`으로 소유권 변경
4. docker-compose up -d --build

그럼 이 후 부터는 설정하신 계정으로 파일이 다운로드 됩니다.
