### ISSUE TITLE
Error: Request failed with status code 400

### ISSUE THREAD

**Issue by bbyongi** [yellowgg2/youngs-ytdl#10]
안녕하세요.
최근 텔레그램 봇에서 유튭 링크를 넣으면 400 에러가 나면서 다운로드 진행이 안되고 있습니다.
Error: Request failed with status code 400

혹시 유튜브 내부가 바뀌어서 youtube-dl이 연동되지 못하는 현상일까요?
만들어주신 서비스 너무 잘쓰고 있는데, 더 이상 사용이 불가능한게 맞는지
혹시 400 에러 해결 가능한지 문의 드립니다.

**Comment by yellowgg2** [comment]
안녕하세요.

만든 저도 자주쓰는거라서 저도 이 문제를일주일 전에 발견하고 코드 업데이트하고 올려놨습니다.

코드 다시 다운 받으셔서 업데이트하시면 기존처럼 동작할거에요

업데이트 방법은 readme 제일 밑 부분 참고하세요. 안되시면 다시 알려주세요

PS. 예상하신데로 유튜브 작동방식이 뭔가 변경이되어 작동이 안되었나봐요

**Comment by bbyongi** [comment]
와 지원 감사 드립니다.
저녁에 퇴근하고 업데이트 해보겠습니다.

**Comment by bbyongi** [comment]
피드백을 이제 드리네요.
지난 주말에 수정해주신 소스 다시 업데이트해서 텔레그램 봇에서 잘 다운로드 되는것 확인 했습니다.
좋은 서비스 계속 사용할 수 있게 해주셔서 감사 드립니다.
