### ISSUE TITLE
질문이 있습니다.

### ISSUE THREAD

**Issue by Alphago777** [yellowgg2/youngs-ytdl#11]
안녕하세요.
먼저 잘 쓰고 있어서 감사하다는 말씀 드립니다.
Error: Request failed with status code 400 때문에
본문 하단에 적어주신대로 재 설치하는 중

Creating ytdl-service ... 
Creating ytdl-download-bot ... error
Creating ytdl-service      ... done
ERROR: for ytdl-download-bot  Cannot create container for service ytdl-download-bot: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for ytdl-download-bot  Cannot create container for service ytdl-download-bot: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.

위와 같이 bot 도커가 설치 되지 않았습니다.
어떻게 조치하면 좋을까요?

**Comment by yellowgg2** [comment]
에러를보니 docker-compose 파일에 볼륨마운트 하시는 부분에 마운트 위치(DOWNLOAD_PATH)를 "."으로만 하셔서 너무 짧다고 에러나오는거 같아요.

"ㆍ/" 로 변경해보시고 이것도 안되면 디렉토리 하나 만드셔서 마운트하셔야 할 것 같습니다

**Comment by Alphago777** [comment]
구글링해서 알아보고
volumes:
      - $DOWNLOAD_PATH/:/ytdlbot/download
      - $SEARCH_ROOT_PATH/:/ytdlbot/searchroot
      - ./bot/db/:/ytdlbot/db
위와같이 : 앞에 / 추가하게끔 변경한 후에 다시 해보니 잘 되네요^^
감사합니다. 잘 쓰겠습니다! 좋은 주말 보내세요.



2023년 3월 10일 (금) 23:07, 알바트로스 ***@***.***>님이 작성:

**Comment by yellowgg2** [comment]
잘되신다니 다행입니다!

좋은 주말 보내세요
