### ISSUE TITLE
채널명과 날짜가 undefined 됩니다.

### ISSUE THREAD

**Issue by zetnox** [yellowgg2/youngs-ytdl#12]
편하게 잘사용하고 있습니다. 감사합니다.
다만 최근들어 유툽 설정이 변경되었는지 채널명과 날짜가 undefined로 표시됩니다. 개선 가능할까요?

**Comment by yellowgg2** [comment]
이건 제가 시간 나는데로 확인해보고 업데이트 해보겠습니다

**Comment by zetnox** [comment]
인스톨 새로하니 이상없이 잘 작동합니다. Ydls 따로 업데이트하가 뭔가 꼬였던듯 합니다.
감사합니다.

**Comment by yellowgg2** [comment]
저도 방금 테스트해봤는데 잘돼서 테스트 하신 주소가 뭔지 여쭤보려고 했거든요.
잘되신다니 다행이네요.
