### ISSUE TITLE
시놀로지 에서 사용시 오류

### ISSUE THREAD

**Issue by kyseong00** [yellowgg2/youngs-ytdl#13]
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /volume1/@docker/tmp/buildkit-mount2471244376/Dockerfile: no such file or directory

라는 오류가 자꾸 나오는대 뭐가 문제일까요....
시놀로지에서 운영중입니다 dsm7.2이고 
https://svrforum.com/nas/695302
이링크의 방법을 응용해서 이용힐려고 합니다

**Comment by yellowgg2** [comment]
지금 코드 다운로드 받으신 경로가 어딘지 모르겠는데요.

`/volume1/@docker/tmp/buildkit-mount2471244376/Dockerfile` 이 위치에 Dockerfile이 없다는 에러입니다. Dockerfile은 소스코드에 포함되어있습니다.

위 경로에 `/volume1/@docker/tmp/buildkit-mount2471244376` 이 폴더에서 소스를 다운로드 받으신게 아니라면, 

경로를 본인 계정의 home 폴더에 다운받으셔서, docker-compose를 실행해보시겠어요?
