### ISSUE TITLE
DS Audio 가 바라보는 위치로 변경이 무슨뜻인지 모르겠습니다.

### ISSUE THREAD

**Issue by ajoc79** [yellowgg2/youngs-ytdl#14]
/volume1/Music 인가요?

예제 좀 알려주세요.

그리고  아래처럼 사용하면 되는 건가요?
시놀로지 제어판->작업 스케쥴러->생성->사용자정의 스크립트
bash /volume1/docker/youngs-ytdl/bot/download-watch.sh

**Comment by yellowgg2** [comment]
DS Audio에 MP3 파일 올리면 저장되는 위치 있죠? 그게 그 위치 입니다.
저는 /volume1/Music인데, @ajoc79 님도 그 위치가 같을지는 장담은 못 드립니다.

시놀로지 웹에 접속하셔서 DS audio의 공유폴더 위치가 어디인지 아실 수 있을겁니다.

그리고, ssh 로 접속하셔서 mp3 파일들이 있는 폴더의 실제 경로를 적어주셔야 해요.

그리고 사용자 정의 스크립트는 코드를 다운 받으신 위치에 `download-watch.sh` 이 파일이 있는 전체 경로를 지정해주시면 됩니다.

위에 쓰신 경로들은 다 제가 쓰는 경로고, @ajoc79 님 나스의 경로는 같을 수 도 있지만 다를 확률이 더 높습니다.

이건 뭐라 답변 드리기 매우 어렵습니다. 리눅스 명령어를 조금 공부하셔야 해요. (ls, cd, pwd 등)
