### ISSUE TITLE
Error 가 납니다....ㅠㅠ

### ISSUE THREAD

**Issue by Alphago777** [yellowgg2/youngs-ytdl#15]
안녕하세요. 개발해 주신 초기부터 잘 쓰고 있습니다. 감사합니다.
아마도 시놀로지 도커에서 컨테이너 매니저로 바뀌고 난 이후 부터인걸로 추정하는데 컨테이너 상에서 로그를 살펴보면
INFO: 12:05:11 172.21.0.2:49958 Download failed GET / (failed download or probe: map[139:exit status 1 140:exit status 1 17:exit status 1 18:exit status 1 22:exit status 1 249:exit status 1 250:exit status 1 251:exit status 1 599:exit status 1 600:exit status 1])
이렇게 나오고 오류가 납니다. 
텔레그램에서도 Error: Request failed with status code 400
이렇게 나오구요..
어떻게 해야 할까요? 도움을 요청드립니다..ㅠㅠ

**Comment by yellowgg2** [comment]
혹시 최근에 업데이트해서 설치 해보신적있을까요?

최근에 저도 같은에러가 발생해서 코드업데이트했습니다

코드 업데이트해서 재설치 해보세요

**Comment by Alphago777** [comment]
답변 감사합니다~ 삭제 후 재설치 중에 에러가 발생하네요...ㅠㅠ
설치 방법 안내 해 주신대로 clone 후 env 파일 편집 한 다음 docker-compose up -d --build 실행했습니다.
Run echo Asia/Seoul 부분에서 에러가 나네요.. 기타 다른 부분은 어떤 문제인지 잘 모르겠어서 텍스트 파일 첨부했습니다..
어떻게 해야 할까요? ㅠㅠ

**Comment by yellowgg2** [comment]
debian linux repo를 못찾아서 발생하는 문제 같습니다.

bot/Dockerfile을 수정하긴 했는데, 다시 pull 하셔서 다시 설치 해보세요.

만약 이것도 같은 에러가 난다면 밑에 그림처럼 `bot/Dockerfile`에 제일 상단에 주석처리 된 두줄 앞에 `#`을 제거 하시고 다시 실행해보세요.

![image](https://github.com/yellowgg2/youngs-ytdl/assets/7078025/023696bc-5178-49c4-a2ee-cce86c7ef98e)

**Comment by Alphago777** [comment]
감사합니다~ 이제 잘 작동합니다. 작은 보답하고 싶어  클리앙으로 쪽지 하나 보냈습니다~^^

**Comment by yellowgg2** [comment]
헉 감사합니다. 보답을 바라고 도움드린건 아닌데... 감사합니다. 잘 쓰겠습니다

**Comment by Alphago777** [comment]
혹시라도!! 쿠폰 등록이 안되면 말씀해주세요! 선물 링크를 복사해서 드리는 방법으로는 처음 보내봐서요
