### ISSUE TITLE
I set own id for admin but bot say what i not admin...

### ISSUE THREAD

**Issue by Jolymmiles** [yellowgg2/youngs-ytdl#17]
I set own id for admin but bot say what i not admin...

**Comment by yellowgg2** [comment]
Did you set `TELEGRAM_ADMIN_USERNAME` in `.env` with your telegramID? 

Can you show me `.env`, only `TELEGRAM_ADMIN_USERNAME` and  telegram id as well in telegram settings? 

Those should be matched except `@`

**Comment by mortal224455** [comment]
안녕하세요
저도 비슷한 문제입니다

빌드까지 다했는데 텔레그램에 메시지 보내도 응답이 없습니다

ADMIN_USERNAME 란에 
1. 텔레그램 닉네임
2. 텔레그램  아이디 @제외한  

무엇을 입력해야 할까요?

**Comment by mortal224455** [comment]
위에 자문 자답

텔레그램  ADMIN_USERNAME  

주석 추가 부탁드립니다 

1. 텔레그램 아이디 입력 (@제외)
2.  대소문자 구문

좋은 프로그램 개발해주셔서 감사합니다

**Comment by yellowgg2** [comment]
> 주석 추가 부탁드립니다

네 주석 추가 해놓을게요
