### ISSUE TITLE
기능문의? 파일 선택시 noti 팝업이나 message 표시 어려울까요?

### ISSUE THREAD

**Issue by bbyongi** [yellowgg2/youngs-ytdl#2]
![F34DAEF9-84B2-42CC-AC72-668262A9C49D](https://user-images.githubusercontent.com/58283298/162116276-af013b7a-0d4f-4ee5-9276-a9ca7f8a18ba.jpeg)

어제 올려주신 최신 버전 설치해서 권한문제 잘 해결된거 확인했습니다.
업데이트 감사 드립니다.

그런데 최신 버전 업데이트해서 사용해 보다가 기능 문의 드립니다.

첨부한 사진처럼...
1. 링크 첨부
2. 봇이 어떤 파일로 받을지 물어봄
3. (1) mp4 터치 -> (2) 상단에 "불러오는중" 표시됨
4. (3) mp3 추가로 터치 -> 아무런 팝업이 없음
5. 잠시 후 확인해 보면 mp4. mp3 둘 다 받아져 있음

위 과정처럼 파일 선택해 받기 시작 할 때 채팅창에 "파일명" downloading... text 메세지나
상단에 "불러오는중" 처럼 팝업 표시되도록 noti 되는건 어려운지 문의 드립니다.

평소에 mp4 종류만 받으면 현재 상태로도 쓰는데 문제가 없겠지만
커버 노래 같은 경우에 mp4랑 mp3를 각각 동시에 받아주는데
처음 파일 선택할때 한번만 상단에 "불러오는중" 표시되고
그 이후로는 noti가 없어서 잘 눌러진건지... 받아지고 있는건지... 
알수가 없어서 불편함이 있습니다.

그렇게 기다렸다가 나중에 보면 다운로드 받았다고 채팅 메세지가 주루루 올라오는데
제가 여러번 터치해서 같은 파일을 여러번 중복으로 다운 받게 되더라구요.

이것저것 계속 귀찮게 해드려 죄송합니다 ㅎㅎ
그만큼 편리한 서비스라 계속쓰고 싶어서 기능 검토 문의 드립니다.

감사합니다.

**Comment by yellowgg2** [comment]
저도 이게 불편해서 기능 이미 추가하였습니다 ㅎㅎ.

다시 최신으로 업데이트 해보세요.

이번 업데이트부터는 git pull 하시고 바로 docker-compose 실행하시면 될거에요

그리고 잘못 받은파일 삭제 기능도 추가했습니다. 자세한 내용은 readme 참고해주세요

**Comment by bbyongi** [comment]
감사합니다. 주말에 업데이트해서 사용해 보겠습니다.
