### ISSUE TITLE
기능문의? mp4와 mp3를 항상 둘다 받을수 있는 옵션 추가는 어려울까요?

### ISSUE THREAD

**Issue by bbyongi** [yellowgg2/youngs-ytdl#3]
만들어주신 텔레그램 봇 덕분에 유투브 보다가 링크를 
텔레봇에게 전달해서 아주 간단하게 다운로드 받고 있습니다.

마지막일듯 싶은데... 
한가지만 더 기능 추가 문의 드립니다.

제가 주로 커버 노래 영상을 mp4랑 mp3를 둘 다 받는 편인데
혹시 /setft 에 both 메뉴 하나 추가해서 both 일때는 mp4랑 mp3를 
둘 다 자동으로 다운로드 할 수 있는 옵션 추가는 어려울지 문의 드립니다.

그렇게 된다면 매번 mp3 랑 mp4 두번씩 터치할 필요 없이
/setft 로 both 설정해두면 파일 타입 선택할 필요없이 알7아서 mp4 mp3 둘 다 받아질테니
상상만해도 너무 편할거 같아서... 기능 문의 드립니다.

**Comment by yellowgg2** [comment]
지금 /setft로 mp3,mp4 등 여러가지 옵션이 동시에 선택이 됩니다.

선택한 타입들은 자동으로 다 한꺼번에 다운로드가 되고 있습니다. 이 기능이 원하시는 기능이 맞으신가요?

**Comment by bbyongi** [comment]
네 맞습니다.
한번에 하나만 선택되는줄 알았는데... 둘다 받아지는지 설정해 보겠습니다.

**Comment by bbyongi** [comment]
이전 버전에서는 /setft 에서 하나만 선택되서 받아져서 건의 드렸던건데
방금 최신 버전으로 업데이트/재설치해서 사용해보니 제가 원하던 기능이 이미 지원되고 있었네요.

/setft 에서 파일 누를때마다 토글 방식으로 추가/삭제가 가능하고
추가된 파일 형식들은 동시에 함께 받아져서 아주 편하게 사용할 수 있을것 같습니다.
그리고 "다운로드 시작합니다." "다운로드 완료" 메세지가 바로 바로 표시되서 너무 좋아졌네요.

좋은 프로그램 만들어주셔서 감사합니다. 잘 쓰겠습니다.

**Comment by bbyongi** [comment]
방금 생각난 질문 한가지 드립니다.
혹시 해상도는 항상 최고 화질로 받아지고 있는게 맞는거죠?
해상도에 대한 언급이 없어서 항상 최고 해상도로 받아지는게 맞는지 궁금합니다.

mp4 영상 받을때 720p, 1080p, 4K 등 해상도 선택하는 옵션 셋팅까지 바라는건... 
좀 너무 욕심일듯 싶기도 하고... 괜히 주말에 숙제 드리는게 아닐까 싶어...
그리고 저만 계속 불평(?)하며 기능 개선 요청드리는 것 같아 더 문의 드리기가 너무 죄송해서
여기까지만 문의 드리겠습니다. ^^;;

**Comment by yellowgg2** [comment]
그게 원하시는 기능이었다니 다행입니다.

그리고 잘 써주셔서 저도 좋네요.

문의하신 해상도를 따로 설정할 수 있는 기능은 없는것 같고 현재는 무조건 최고 해상도로 받게 되어 있는 것 같습니다.

해상도 변경 옵션은 수정하는게 좀 까다로울 수도 있겠네요. ydls에 아예 없는 기능이라서요. 차근 차근 알아보도록 하겠습니다

그리고 개선 사항은 언제든 알려주시면 항상 참고하도록 하겠습니다. 그래야 저도 편하게 쓰거든요 ㅎㅎ

그럼 즐거운 주말되세요
