### ISSUE TITLE
혹시 플레이리스트로 다운받을 수 있는 기능이 있을까요?

### ISSUE THREAD

**Issue by ncae95** [yellowgg2/youngs-ytdl#4]
개발해주신 덕분에 잘 사용하고 있습니다! 

다름이 아니라 제가 유튜브의 플레이 리스트를 다운받고자 할 떄가 가끔 있는데요.
플레이리스트를 받으면(e.g. https://youtube.com/playlist?list=PLo2ZIWlO1BLSlojtYHemWHGvuPRb3DZyK) 에러(Error:Request failed with status code 400)가 뜹니다. 
원래 설계상(?) 플레이리스트를 다운받을 수는 없는걸까요?
도커 로그로는 
INFO: 00:36:15 172.20.0.3:43720 Download failed GET / (playlist when expected a single entry) 입니다.

**Comment by yellowgg2** [comment]
요건 한번 알아보도록 하겠습니다.

아마 되더라도 mp3로만 다운될 듯 하네요

**Comment by yellowgg2** [comment]
다시 보니 잘하면 모든 포멧으로 다운로드 받을 수 있게 할 수 있겠네요.

업데이트 되면 업로드 하도록 하겠습니다.

**Comment by ncae95** [comment]
! 감사합니다 !!!!!

**Comment by yellowgg2** [comment]
업데이트 했습니다. 업데이트 내용은 [release note](https://github.com/yellowgg2/youngs-ytdl/releases/tag/1.1)를 참고해주세요.

**Comment by bbyongi** [comment]
플레이 리스크까지 지원되다니 감사합니다.
업데이트해서 사용해 보겠습니다

**Comment by ncae95** [comment]
업데이트 하니까 플레이리스트 지원하네요.
정말 감사합니다 ㅎㅎ!!!
