### ISSUE TITLE
플레이 리스트 다운 취소 문의? /help 문의?

### ISSUE THREAD

**Issue by bbyongi** [yellowgg2/youngs-ytdl#5]
안녕하세요.
플레이리스트 기능 사용하다가 기능 문의 드립니다.

Q1. 제가 플레이 리스트 90개 짜리를 봇에게 보내서
90개 mp4/mp3 다운로드가 시작되었는데....
중간에 플레이 리스트 다운로드를 멈추고 싶은데 방법을 모르겠습니다.

![Uploading 8282B026-F30E-4947-9745-A2929E3C6131.jpeg…]()

혹시 플레이 리스트 다운로드 진행중에 취소/중지 할 수 있는 방법이 있을까요?
아니면 추가로 다운 취소 구현 검토되어야 하는지요.

앞으로 몇개나 남았는지 체크도 가능하면 좋을것 같은데...
너무 구현하시는데 귀찮은 기능 요청이려나요. ㅎㅎ

Q2. 두번째 질문은 /help 에 /udtof 랑 /chtof 커맨드가 표시되지 않고 있는데
어쩌다 설정하는거라 커맨드를 자꾸 까먹어서
/help 에는 모든 커맨드를 표시해 주시면 안될지 문의 드립니다.

Q3. 다운로드 완료 메세지 내에 파일 용량 표시할수 있는 옵션 추가는 어려울까요?
다운받은 파일 크기가 얼마나 되는지 궁금해서.. 용량 MB 단위로 표시되면 좋을것 같아 건의 드립니다.

사용하면서 아쉬운 부분들 또 기능 개선 요청드리는거 같아 죄송합니다.
좋은 프로그램 만들어주셔서 정말 감사합니다.

**Comment by yellowgg2** [comment]
1. 플레이리스트 중간 취소는 구현해야합니다. 구현 가능합니다
2. 남은 갯수 표시도 구현가능합니다
3. `chtof, udtof`등은 어드민 메뉴라 `/ahelp` 명령치시면 볼 수 있어요. 봇이 다중 사용자가 가능해서 이렇게 구분 해놨습니다. 제가 이걸 README에 썼는 줄 알았는데 빼먹었네요
5. 용량 표시도 구현 가능합니다

결과적으로 1,2,4 번은 구현이 필요한 사항입니다.

개선 사항은 언제나 환영합니다 ㅎㅎ

**Comment by yellowgg2** [comment]
@bbyongi 구현 완료 되었습니다.

자세한 사항은 [Release Note](https://github.com/yellowgg2/youngs-ytdl/releases/tag/1.3) 또는 [README](https://github.com/yellowgg2/youngs-ytdl)를 참고하세요.

**Comment by bbyongi** [comment]
기능 추가 감사합니다.
업데이트 해서 써보니 용량 표시는 잘 되는걸 확인했습니다.
그런데 플레이 리스트 받기가 동작되지 않는것 같습니다.

플레이 리스트를 링크를 봇에게 전달해도 "플레이 리스트를 검색 중입니다",
"플레이 리스트를 검색 완료. (90개 항목)" 문구가 안뜨고 
첫번째 영상 1개만 받아지는듯 합니다.

**Comment by yellowgg2** [comment]
흠.. 모든 케이스를 다 테스트해봤는데 잘 되는데요.

그럴 일은 없겠지만, 지금 버전이 설정을 docker-compose.yml로 안하고 같은 폴더에 있는 .env로 하도록 변경되었습니다.

그래서 아래 순서대로 한번 업데이트를 진행 다시 해보시겠어요?

1. 지금 사용하는 docker-compose.yml에 있는 변경한 내용을 메모장에 복사
2. `git checkout -- .` 명령으로 변경된 내용을 기존 내용으로 복원
3. `git pull origin master`로 최신코드 받기
4. 메모장에 붙여넣은 값들을 docker-compose.yml과 같은 경로에 있는 `.env`에 대응되는 값에 넣기
5. `docker-compose down && docker-compose up -d --build`로 재설치

만약 위 방법으로 현상이 똑같이 나온다면  
다시 말씀해주세요

**Comment by bbyongi** [comment]
그냥 git pull, docker-compose up -d --build 로 재빌드 재적용 했었는데...
말씀처럼 깔끔하게 모든 설정 지우고 다시 docker-compose up -d --build 로 설치해 보겠습니다.

**Comment by bbyongi** [comment]
차이점을 찾은것 같습니다.

< 문제점 >
youtube 메뉴에서 공유 기능으로 플레이 리스트 주소를 얻으면 youtu.be 축약형 주소로 얻어지고
youtu.be/gxb926KhG0c 축약형 주소에는 "playlist?list" 키워드가 없어서 리스트가 아닌 단일 동영상으로 인식되는것 같습니다.
-> 축약형 list 주소 인식 못함 https://youtu.be/gxb926KhG0c?list=???????

< 해결방법 >
릴리즈 노트 적어주신걸 보니 봇에게 전달하는 플레이 리스트 주소에 "playlist?list" 키워드가 필요한 것 같아서
위 축약형 주소를 https://www.youtube.com/playlist?list=??????? 로 임의로 바꿔서 봇에게 전달하니
"플레이 리스트를 검색 중입니다."가 뜨면서 플레이 리스트가 잘 인식되네요.

원본 (축약형 주소) : https://youtu.be/gxb926KhG0c?list=???????
수정 (playlist?list 포함되도록 주소 수정) : https://www.youtube.com/playlist?list=???????

일단 해결 방법을 찾았으니 https://www.youtube.com/playlist?list= 형식으로 봇에게 전달하여 사용해 보겠습니다.

**Comment by yellowgg2** [comment]
일단 해결되었다니 다행이네요.

조금 더 해보시고 문제점 나오면 알려주세요
