### ISSUE TITLE
"ENAMETOOLONG: name too long, open" 에러 문의

### ISSUE THREAD

**Issue by bbyongi** [yellowgg2/youngs-ytdl#6]
플레이리스트 다운로드 중에 error 발생하면서 캔슬되었습니다.

https://youtu.be/dq4ObnvbH28

위 링크 봇에게 전달하면 "ENAMETOOLONG: name too long, open" 에러가 뜨면서
플레이 리스트 다운받던게 멈춰버리네요.

😊 다운로드를 시작합니다.[mp3] 

👿 ENAMETOOLONG: name too long, open './download/버블디아/버블디아_20190628_3키업⬆️아름답게 사랑하는 날까지 커버 - 김경호 (여자버전으로 불러보았어요!)  버블디아.mp3'

확인 부탁 드립니다.

**Comment by yellowgg2** [comment]
이건 os가 지원하는 최대 파일 길이가 있습니다. 그 파일 길이를 넘어서 저장하려고 해서 발생하는 문제인데 강제로 파일 이름을 줄이는 수 밖에 없는데요.

지금 현재 해볼 수 있는 방법은 

- 파일 이름에서 채널 이름과 날짜를 뺀 상태로 다운로드를 해보시거나
- 짧은 제목을 가진 같은 영상을 찾아 다운로드하는 수 밖에 없습니다.

**Comment by bbyongi** [comment]
혹시 최대 길이를 넘어선 경우라면 overflow된 뒷부분을 잘라내고 저장될순 없을까요?

만약 채널명과 업로드날짜 옵션을 끄고 위 영상은 넘어가더라도
나중에 다른 제목 긴 영상이 또 있으면 해결이 안될거 같은데....

만약 최대 길이 초과시 ... 등으로 초과된 뒷부분을 짤라내서 저장해 주시면 
앞부분 정보만으로도 유투브에서 검색해서 찾아볼 수 있으니
제목이 길어서 다운로드 실패하는 것보다 제목 뒷부분이 짤래내서 저장되면 좋을 것 같습니다.

**Comment by yellowgg2** [comment]
네 그 정도는 쉽게 가능할 것 같습니다.

우선 끝에 `...` 으로는 불가능하고, 특정 단어로 대체하도록 하겠습니다. `toolong`이라던지...

**Comment by yellowgg2** [comment]
업데이트 했습니다.

파일이름이 90자가 넘어가는 경우 뒤를 자르고 `-toolong`을 파일이름에 붙이고, 다운로드를 하도록 했습니다

git pull 하셔서 업데이트 하시면 되요

**Comment by bbyongi** [comment]
업데이트 너무 감사 드립니다.
다시 안끊기고 파일 잘 받아지는지 확인해 보겠습니다.

**Comment by bbyongi** [comment]
기존에 받았던 리스트가 에러로 다운로드가 끊겨서
다 삭제하고 다시 받아보니 파일명 too long 에러 뜨지 않고
잘 받아지네요.
수정해주셔서 정말 감사합니다.
