### ISSUE TITLE
Error: Request failed with status code 400

### ISSUE THREAD

**Issue by Alphago777** [yellowgg2/youngs-ytdl#7]
안녕하세요.
우연히 클리앙 게시글 보고 도커의 ㄷ자도 모르던 제가 몇일간 실패를 거듭하다 설치를 마쳤습니다. ㅎ
좋은 프로그램 정말 감사합니다.
이용하는던 중에 "Error: Request failed with status code 400" 이란 메세지가 나오고 다운로드 실패하는 사례가 있었습니다.
https://www.youtube.com/watch?v=AFNBRnUZqrE
위 영상인데요.. 아마도 연령 제한 동영상 이어서 그런 것 같습니다.
우회하는 법을 구글링 해 봤는데 몇몇 방법이 있지만 대부분 막힌 것 같고요..
이런 경우는 조치가 어려울까요?

**Comment by yellowgg2** [comment]
아... youtube에서 막거나 뭔가 인증 절차가 있어야 하는 동영상은 저도 어찌할 방법이 없습니다.

**Comment by Alphago777** [comment]
그렇군요..^^
아쉽지만 그런 동영상은 다른 방법을 이용해야겠네요.
감사합니다~!

**Comment by Alphago777** [comment]
아참! 한가지 기능제안 드려도 될까요?
현재 ffmpeg로 유튜브 영상 다운받는 확장자가 1080p 까지만 mp4 지원하고 그 이상인 1440p 나 2160p 는 webm만 지원하는 걸로 알고있는데요.. 
보통 최고 해상도로 저장하고자 하는 이용자가 많을 것 같은데 setft에 옵션을 둬서 1080p가 최대 해상도면 mp4,로, 1440p나 2160p가 최고 해상도면 webm으로 자동 선택되어 다운로드 할 수 있는 옵션도 가능할까요?
제안 드려봅니다..^^

**Comment by yellowgg2** [comment]
이건 한번 알아보도록 하겠습니다. Ydls가 해상도 정보를 가지고 있으면 가능할 수도 있겠네요
