### ISSUE TITLE
혹시 ARM 코어에서 sudo docker-compose up -d --build 에러나는 현상

### ISSUE THREAD

**Issue by bbyongi** [yellowgg2/youngs-ytdl#8]
안녕하세요.
그동안 오라클 프리티어의 AMD ubuntu 20.04 에서 git 소스 내려받고
sudo docker-compose up -d --build 으로 빌드해서 잘 사용하고 있었는데...

ARM 코어로 인스턴스 변경하여 ubuntu 20.04에서 도커 빌드로 설치하려고 하는데
아래와 같이 Step 37/40 : RUN 에서 error가 발생하고 있습니다.

[build_error.txt](https://github.com/yellowgg2/youngs-ytdl/files/8815933/build_error.txt)

```
Step 37/40 : RUN     ffmpeg -version &&     ffprobe -version &&     yt-dlp --version &&     ydls -version
 ---> Running in 6ee209009968
/usr/local/bin/ffmpeg: line 1: syntax error: unexpected "("
ERROR: Service 'ytdl-service' failed to build: The command '/bin/sh -c ffmpeg -version &&     ffprobe -version &&     yt-dlp --version &&     ydls -version' returned a non-zero code: 2
```

혹시 위 error가 ARM 코어에서 빌드 불가능한 상황이 맞는건가요?

아니면 최신 ffmpeg 관련해서 뭔가 문제가 있는건지....

기존에 잘 빌드했던 AMD 인스턴스가 삭제되어, 다시 확인해보지 못해서
ARM 코어에서는 youngs-ytdl를 사용할 수 없는건지 궁금하여 문의 드립니다.

**Comment by yellowgg2** [comment]
아마 arm에서는 빌드 안되는게 맞을거에요.

arm에서 빌드되게하려면 연관 패키지들을 다 arm용으로 받아서 빌드해야하는데 그건 따로 작업해야하는데 제가 그걸 해본적이 없어서 따로 하진않았거든요

**Comment by bbyongi** [comment]
아... 그동안 오라클 AMD 1C/1G 인스턴스 사용하면서 youngs-ytdl 빌드해서 잘 사용했는데
이번에 AMD 4C/24G 인스턴스로 바꾸면서 arm64 로 바뀌어 youngs-ytdl을 사용할 수 없게 되었네요.
너무 편하고 좋았는데... arm 환경에서 사용할 수 없는게 너무 아쉽습니다.
